# Uncomment this line to define a global platform for your project

inhibit_all_warnings!

platform :ios, '8.0'

# Uncomment this line if you're using Swift
# use_frameworks!

target 'shenbianapp' do
 
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'AMap2DMap'
pod 'AMapLocation'
pod 'AMapSearch'
pod 'YYKit'

#pod 'ReactiveCocoa', '~> 2.0'
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'

pod 'Masonry'
pod 'IQKeyboardManager'
pod 'Qiniu', '~> 7.2.2'
pod 'RongCloudIM', '~> 2.8.15'
pod 'WechatOpenSDK'

end


