# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

# Uncomment this line if you're using Swift
# use_frameworks!

target 'shenbianapp' do
 
pod 'AFNetworking-RACExtensions', '~> 0.1.8'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'AMap2DMap' 
pod 'AMapSearch'
pod 'YYKit', '~> 1.0.7'
pod 'ReactiveCocoa', '~> 2.0'
pod 'Masonry', '~> 1.0.1'
pod 'IQKeyboardManager', '~> 4.0.7'
pod 'Qiniu', '~> 7.0.1'


end


